### ISSUE TITLE
Resistor necessary?

### ISSUE THREAD

**Issue by git3smurf** [Jpipe001/METAR#2]
When I use an ESP32 with an ALITOVE WS2811 Pixels Individually Addressable RGB lightchain would a resistor between it also necessary/advisable?

Kind regards,

Git3

**Comment by G6EJD** [comment]
It would only need a resistor if the WS2811 input load was too high thereby drawing too much current from the ESP32 output pin. But they are both CMOS types so there shouldn’t be any problem.

**Comment by Jpipe001** [comment]
A resistor is to limit the current and is not strictly necessary, but is advisable if a short on the led chain occurred.
If there was a bad connection on the LEDS (data line), then there is a possibility they could ALL come on at full brightness and that could cause an overload depending on the number of LEDS.

**Comment by git3smurf** [comment]
Found some other sources to that advised also to place 200 - 500 Ohms resistor on the data-line and a capacitor over the 5v/GND feed to the leds... most other sources however mention a different type of capacitor: 1000µF capacitor.

**Comment by Jpipe001** [comment]
The value of the resistor is not critical, I use a 330 Ohm.
The value of the smoothing Capacitor is also not critical,  470µF capacitor will do.
