### ISSUE TITLE
While compiling: error: 'ssid' was not declared in this scope  / error: 'password'was not declared in this scope   

### ISSUE THREAD

**Issue by git3smurf** [Jpipe001/METAR#3]
DoubleChecked settings in the lines 100-105, they seem to me ok. ...  As I was compiling I ran in to these errors related to these settings: 

In file included from c:\Users\user\OneDrive\Documenten2\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:89:
c:\Users\user\OneDrive\Documenten2\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino: In function 'void setup()':
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:294:14: **error: 'ssid' was not declared in this scope**
   WiFi.begin(ssid, password);
              ^~~~
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:294:14: note: suggested alternative: 'setsid'
   WiFi.begin(ssid, password);
              ^~~~
              setsid
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:294:20: **error: 'password' was not declared in this scope**
   WiFi.begin(ssid, password);
                    ^~~~~~~~
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:294:20: note: suggested alternative: 'makeWord'
   WiFi.begin(ssid, password);
                    ^~~~~~~~
                    makeWord
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino: In function 'void Network_Status()':
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:553:83: **error: 'ssid' was not declared in this scope**
   if (WiFi.status() == 3 ) Serial.printf("= 3 ~ Connected to %s Router\n", String(ssid).c_str());
                                                                                   ^~~~
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:553:83: note: suggested alternative: 'setsid'
   if (WiFi.status() == 3 ) Serial.printf("= 3 ~ Connected to %s Router\n", String(ssid).c_str());
                                                                                   ^~~~
                                                                                   setsid
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino: In function 'void Go_Server(void*)':
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:2278:68: **error: 'ssid' was not declared in this scope**
                   html_code += "<BR>Connected to &nbsp: " + String(ssid);
                                                                    ^~~~
C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:2278:68: note: suggested alternative: 'setsid'
                   html_code += "<BR>Connected to &nbsp: " + String(ssid);
                                                                    ^~~~
                                                                    setsid
Multiple libraries were found for "WiFi.h"
  Used: C:\Users\user\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\WiFi
  Not used: C:\Users\user\OneDrive\Documenten2\Arduino\libraries\WiFiEspAT
exit status 1

Compilation **error: 'ssid' was not declared in this scope**

**Comment by Jpipe001** [comment]
//  ################   CONFIGURE YOUR SETTINGS HERE  ################

/* Please Modify the "Your Network Name and Your Network Password" To suit your Project */
const char*      ssid = "Your Network Name";          // your network SSID (Name) ~ Network Example
const char*  password = "Your Network Password";      // your network Password

//const char*      ssid = "iPhone";          // your network SSID (Name) ~ iPhone Example
//const char*  password = "johnjohn";        // your network Password

/* Please Modify the "No_Stations and LED_TYPE and COLOR_ORDER" To suit your Project */
// Set Up LEDS   ***   Connect LEDS to Ground & 5 Volts on ESP32 pins (There are Varients, so Check)
#define No_Stations          52      // Number of LEDs / Number of Stations
#define LED_TYPE         WS2812      // WS2811 or WS2812 or NEOPIXEL
#define COLOR_ORDER         GRB      // WS2811 are RGB or WS2812 are GRB or NEOPIXEL are CRGB
#define DATA_PIN              5      // Connect LED Data Line to pin D5/P5/GPIO5  *** With CURRENT LIMITING 220 to 330 Ohm Resistor in Line ***
#define NUM_LEDS    No_Stations      // Number of LEDs
#define BRIGHTNESS           16      // Master LED Brightness (<12=Dim 16~20=ok >20=Too Bright) Set as required
#define FRAMES_PER_SECOND   120
CRGB leds[NUM_LEDS];                 // Color Order for LEDs ~ CRGB for Displaying Gradients


**Syntax is usually the problem**.

Please check the "Your Network Name and Your Network Password".
If you haven't done so already, delete the // in front of "const char*
Only one ssid and password are required.

If you are using WS2811 LEDS, Please change to:
#define LED_TYPE         WS2811      // WS2811 or WS2812 or NEOPIXEL
#define COLOR_ORDER         RGB      // WS2811 are RGB or WS2812 are GRB or NEOPIXEL are CRGB

To get a program message  is normal, This always comes up so just ignore it:
In file included from c:\Users\user\OneDrive\Documenten2\Arduino\libraries\FastLED\src/FastLED.h:75,
from C:\Users\user\Downloads\arduino\metar program\METAR_ESP32A_11_24_23\METAR_ESP32A_11_24_23.ino:89:
c:\Users\user\OneDrive\Documenten2\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined. All SPI access will default to bitbanged output

Please contact me directly, see line 73 of your code, I will be glad to help.
If this fixes it or you have additional problems.
Thanks
John
